<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreDeliveryScheduleRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()->can('create', \App\Models\DeliverySchedule::class);
    }

    public function rules(): array
    {
        return [
            'ds_code' => 'nullable|string|unique:delivery_schedules,ds_code|max:255',
            'job_order_id' => 'required|exists:job_orders,id',
            'product_id' => 'nullable|exists:products,id',
            'ds_status' => 'nullable|in:BACKLOG,ON SCHEDULE,DELIVERED,CANCELLED',
            'ppqc_status' => 'nullable|string|max:255',
            'delivery_date' => 'required|date|after_or_equal:today',
            'delivery_time' => 'nullable|date_format:H:i',
            'week_number' => 'nullable|integer|min:1|max:53',
            'date_encoded' => 'nullable|date',
            'quantity' => 'required|integer|min:1',
            'max_quantity' => 'nullable|integer|min:0',
            'delivered_quantity' => 'nullable|integer|min:0',
            'transfer_quantity' => 'nullable|integer|min:0',
            'fg_stocks' => 'nullable|integer|min:0',
            'buffer_stocks' => 'nullable|integer|min:0',
            'jo_balance' => 'nullable|integer|min:0',
            'pmp_commitment' => 'nullable|string',
            'ppqc_commitment' => 'nullable|string',
            'remarks' => 'nullable|string',
            'delivery_remarks' => 'nullable|string',
            'jo_remarks' => 'nullable|string',
        ];
    }

    public function prepareForValidation(): void
    {
        // DS code is auto-generated by the model's boot method, don't generate it here

        // Auto-calculate week_number from delivery_date if not provided
        if (!$this->week_number && $this->delivery_date) {
            $this->merge([
                'week_number' => (int) date('W', strtotime($this->delivery_date)),
            ]);
        }

        // Set default ds_status if not provided
        if (!$this->ds_status) {
            $this->merge(['ds_status' => 'ON SCHEDULE']);
        }

        // Set date_encoded to today if not provided
        if (!$this->date_encoded) {
            $this->merge(['date_encoded' => now()->toDateString()]);
        }

        // Initialize default quantities
        $defaults = [
            'fg_stocks' => 0,
            'buffer_stocks' => 0,
            'jo_balance' => 0,
            'max_quantity' => 0,
        ];

        foreach ($defaults as $key => $value) {
            if (!$this->has($key)) {
                $this->merge([$key => $value]);
            }
        }

        // Enforce delivery time window (08:00 - 17:00) if provided
        if ($this->delivery_time) {
            $time = \DateTime::createFromFormat('H:i', $this->delivery_time);
            if (!$time) return;
            $hourMinute = $time->format('H:i');
            if ($hourMinute < '08:00' || $hourMinute > '17:00') {
                $this->merge(['_delivery_time_error' => true]);
            }
        }
    }

    public function withValidator($validator)
    {
        $validator->after(function ($validator) {
            if ($this->has('_delivery_time_error')) {
                $validator->errors()->add('delivery_time', 'Delivery time must be between 08:00 and 17:00.');
            }
        });
    }
}