<?php

namespace App\Http\Controllers;

use App\Models\EndorseToLogistic;
use App\Models\Product;
use App\Models\JobOrder;
use App\Http\Requests\StoreEndorseToLogisticRequest;
use App\Http\Requests\UpdateEndorseToLogisticRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class EndorseToLogisticController extends Controller
{
    public function index(Request $request)
    {
        $this->authorize('viewAny', EndorseToLogistic::class);

        $query = EndorseToLogistic::with(['deliverySchedule.jobOrder.product', 'product']);

        if ($request->filled('search')) {
            $search = $request->search;
            $query->where('etl_code', 'like', "%{$search}%")
                  ->orWhere('product_code', 'like', "%{$search}%")
                  ->orWhere('customer_name', 'like', "%{$search}%");
        }

        $endorsements = $query->latest('date')->paginate(15);

        $products = Product::select('id', 'product_code', 'model_name')
            ->orderByRaw("COALESCE(model_name, product_code) ASC")
            ->get();

        return view('endorse-to-logistics.index', compact('endorsements', 'products'));
    }

    public function create()
    {
        $this->authorize('create', EndorseToLogistic::class);

        $jobOrders = JobOrder::with('product')
            ->whereIn('jo_status', ['Approved', 'In Progress', 'JO Full'])
            ->orderBy('jo_number', 'desc')
            ->get();

        return view('endorse-to-logistics.create', compact('jobOrders'));
    }

    public function store(StoreEndorseToLogisticRequest $request)
    {
        $this->authorize('create', EndorseToLogistic::class);

        try {
            DB::beginTransaction();

            $validated = $request->validated();

            // Get job order if provided to auto-fill product details
            if (isset($validated['job_order_id']) && $validated['job_order_id']) {
                $jobOrder = JobOrder::findOrFail($validated['job_order_id']);
                // Auto-fill product fields from job order
                $validated['product_code'] = $validated['product_code'] ?? $jobOrder->product_code;
                $validated['customer_name'] = $validated['customer_name'] ?? $jobOrder->customer_name;
                $validated['model_name'] = $validated['model_name'] ?? $jobOrder->model_name;
                $validated['description'] = $validated['description'] ?? $jobOrder->description;
                $validated['uom'] = $validated['uom'] ?? $jobOrder->uom;
                $validated['total_out'] = $validated['total_out'] ?? $jobOrder->jo_balance;
                $validated['quantity'] = $validated['quantity'] ?? $jobOrder->jo_balance;
            }

            // Get product directly if provided
            if (isset($validated['product_id']) && $validated['product_id']) {
                $product = Product::findOrFail($validated['product_id']);
                // Auto-fill if not provided
                $validated['product_code'] = $validated['product_code'] ?? $product->product_code;
                $validated['customer_name'] = $validated['customer_name'] ?? $product->customer_name ?? '';
                $validated['model_name'] = $validated['model_name'] ?? $product->model_name ?? '';
                $validated['description'] = $validated['description'] ?? $product->description ?? '';
                $validated['uom'] = $validated['uom'] ?? ($product->uom ?? 'PC/S');
            }

            // ETL code will be auto-generated by the model's boot method

            // Set encoded user
            $validated['encoded_by'] = auth()->id();
            $validated['date_encoded'] = now();

            // Set default date and time if not provided
            $validated['date'] = $validated['date'] ?? now()->toDateString();
            $validated['time'] = $validated['time'] ?? now()->toTimeString();
            $validated['status'] = $validated['status'] ?? 'pending';

            $endorse = EndorseToLogistic::create($validated);

            // Try to associate this endorsement with an existing DeliverySchedule
            try {
                if (empty($endorse->delivery_schedule_id) && $endorse->product_id) {
                    $matchQuery = \App\Models\DeliverySchedule::where('product_id', $endorse->product_id);
                    if ($endorse->delivery_date) {
                        $matchQuery->whereDate('delivery_date', $endorse->delivery_date);
                    }
                    // prefer exact quantity match when possible
                    if ($endorse->quantity) {
                        $matchQuery->where('quantity', $endorse->quantity);
                    }

                    $matched = $matchQuery->first();
                    if ($matched) {
                        $endorse->delivery_schedule_id = $matched->id;
                        $endorse->save();
                    }
                }
            } catch (\Throwable $e) {
                // non-fatal: log and continue
                Log::warning('Failed to auto-associate endorsement to delivery schedule: ' . $e->getMessage(), ['endorse_id' => $endorse->id]);
            }

            DB::commit();

            return redirect()->route('endorse-to-logistics.index')
                ->with('success', 'Record created successfully.');

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Endorse To Logistics creation failed: ' . $e->getMessage(), [
                'user_id' => auth()->id(),
                'exception' => $e
            ]);

            return back()->withInput()->with('error', 'Failed to create record: ' . $e->getMessage());
        }
    }

    public function edit(EndorseToLogistic $endorseToLogistic)
    {
        $this->authorize('update', $endorseToLogistic);

        $jobOrders = JobOrder::with('product')
            ->whereIn('jo_status', ['Approved', 'In Progress', 'JO Full'])
            ->orderBy('jo_number', 'desc')
            ->get();

        return view('endorse-to-logistics.edit', compact('endorseToLogistic', 'jobOrders'));
    }

    public function update(UpdateEndorseToLogisticRequest $request, EndorseToLogistic $endorseToLogistic)
    {
        $this->authorize('update', $endorseToLogistic);

        try {
            DB::beginTransaction();

            $old = $endorseToLogistic->toArray();
            $endorseToLogistic->update($request->validated());

            DB::commit();

            return redirect()->route('endorse-to-logistics.index')
                ->with('success', 'Record updated successfully.');

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Endorse To Logistics update failed: ' . $e->getMessage(), [
                'user_id' => auth()->id(),
                'id' => $endorseToLogistic->id
            ]);

            return back()->withInput()->with('error', 'Failed to update record.');
        }
    }

    public function destroy(EndorseToLogistic $endorseToLogistic)
    {
        $this->authorize('delete', $endorseToLogistic);

        try {
            DB::beginTransaction();

            $endorseToLogistic->delete();

            DB::commit();

            return redirect()->route('endorse-to-logistics.index')
                ->with('success', 'Record deleted successfully.');

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Endorse To Logistics deletion failed: ' . $e->getMessage(), [
                'user_id' => auth()->id(),
                'id' => $endorseToLogistic->id
            ]);

            return back()->with('error', 'Failed to delete record.');
        }
    }

    /**
     * Approve an endorsement to logistics
     */
    public function approve(EndorseToLogistic $endorseToLogistic)
    {
        $this->authorize('update', $endorseToLogistic);

        try {
            DB::beginTransaction();

            $endorseToLogistic->update([
                'status' => 'approved',
                'approved_at' => now(),
                'approved_by' => auth()->id(),
            ]);

            DB::commit();

            // If request expects JSON (AJAX), return JSON so frontend can update UI inline
            if (request()->wantsJson() || request()->ajax()) {
                return response()->json([
                    'success' => true,
                    'status' => 'approved',
                    'delivery_schedule_id' => $endorseToLogistic->delivery_schedule_id,
                    'message' => 'Endorsement approved successfully. Ready for delivery.'
                ]);
            }

            return back()->with('success', 'Endorsement approved successfully. Ready for delivery.');

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Endorsement approval failed: ' . $e->getMessage(), [
                'user_id' => auth()->id(),
                'id' => $endorseToLogistic->id
            ]);

            return back()->with('error', 'Failed to approve endorsement.');
        }
    }

    /**
     * Dispatch an approved endorsement (mark as in progress/on delivery)
     */
    public function dispatch(EndorseToLogistic $endorseToLogistic)
    {
        $this->authorize('update', $endorseToLogistic);

        try {
            DB::beginTransaction();

            // Only allow dispatching approved endorsements
            if ($endorseToLogistic->status !== 'approved') {
                if (request()->wantsJson() || request()->ajax()) {
                    return response()->json(['success' => false, 'message' => 'Only approved endorsements can be dispatched.'], 422);
                }
                return back()->with('error', 'Only approved endorsements can be dispatched.');
            }

            $endorseToLogistic->update([
                'status' => 'in_progress',
                'updated_by' => auth()->id(),
            ]);

            // If this endorsement references a delivery schedule, update that schedule so dashboard logic picks up the change
            try {
                if ($endorseToLogistic->delivery_schedule_id) {
                    $delivery = \App\Models\DeliverySchedule::find($endorseToLogistic->delivery_schedule_id);
                    if ($delivery) {
                        // touch or recalculate status so the UI can reflect relation
                        $delivery->updateDeliveryStatus();
                        $delivery->save();
                    }
                }
            } catch (\Throwable $e) {
                Log::warning('Failed to update delivery schedule after dispatch: ' . $e->getMessage(), ['endorse_id' => $endorseToLogistic->id]);
            }

            DB::commit();

            if (request()->wantsJson() || request()->ajax()) {
                return response()->json([
                    'success' => true,
                    'status' => 'in_progress',
                    'delivery_schedule_id' => $endorseToLogistic->delivery_schedule_id,
                    'message' => 'Endorsement dispatched for delivery.'
                ]);
            }

            return back()->with('success', 'Endorsement dispatched for delivery.');

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Endorsement dispatch failed: ' . $e->getMessage(), [
                'user_id' => auth()->id(),
                'id' => $endorseToLogistic->id
            ]);

            return back()->with('error', 'Failed to dispatch endorsement.');
        }
    }

    /**
     * Mark an endorsement as complete after delivery
     */
    public function complete(EndorseToLogistic $endorseToLogistic)
    {
        $this->authorize('update', $endorseToLogistic);

        try {
            DB::beginTransaction();

            $endorseToLogistic->update([
                'status' => 'completed',
                'completed_at' => now(),
                'completed_by' => auth()->id(),
            ]);

            DB::commit();

            return back()
                ->with('success', 'Endorsement marked as complete.');

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Endorsement completion failed: ' . $e->getMessage(), [
                'user_id' => auth()->id(),
                'id' => $endorseToLogistic->id
            ]);

            return back()->with('error', 'Failed to mark endorsement as complete.');
        }
    }

    public function export()
    {
        $this->authorize('viewAny', EndorseToLogistic::class);

        $data = EndorseToLogistic::with('jobOrder', 'product')->get();
        
        $headers = [
            'Content-Type' => 'text/csv; charset=utf-8',
            'Content-Disposition' => 'attachment; filename=endorsements_' . now()->format('Y-m-d_His') . '.csv',
        ];
        
        $callback = function() use ($data) {
            $file = fopen('php://output', 'w');
            fwrite($file, chr(0xEF) . chr(0xBB) . chr(0xBF));
            
            fputcsv($file, ['Endorsement Number', 'Job Order', 'Customer Name', 'Product Code', 'Model Name', 'Quantity', 'Status', 'Approved By', 'Approved At', 'Source', 'Destination', 'Created At']);
            
            foreach ($data as $row) {
                fputcsv($file, [
                    $row->etl_number ?? '',
                    $row->jobOrder?->jo_number ?? '',
                    $row->customer_name ?? '',
                    $row->product_code ?? '',
                    $row->model_name ?? '',
                    $row->quantity ?? 0,
                    $row->status ?? '',
                    $row->approved_by ?? '',
                    $row->approved_at?->format('Y-m-d H:i:s') ?? '',
                    $row->source ?? '',
                    $row->destination ?? '',
                    $row->created_at?->format('Y-m-d H:i:s') ?? '',
                ]);
            }
            fclose($file);
        };
        
        return response()->stream($callback, 200, $headers);
    }
}